kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: k8s-demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: k8s-demo-pod
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: docker-registry.teambition.net/teambition/k8s-demo:latest
        ports:
        - name: helloworld
          containerPort: 8080
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
