kind: Service
apiVersion: v1
metadata:
  namespace: helloworld
  name: k8s-demo-service
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
